In [3]:
#type hint,function一訂要加型別提示

def add(a:int|float,b:int|float) ->int|float:
    return a+b
def multiply(a:int|float,b:int|float) ->int|float:
    return a*b

add(5,20)
multiply(80,50)

4000

# 第8堂-課業練習
# 計算BMI
- 輸入:
-   1)請輸入姓名:xxxx
-   2)請輸入身高(cm):
-   3)請輸入體重(kg):
 
- 請使用自訂的function
- 1)建立bmi的function,會傳出bmi
- 2)建立get_status,會傳出字串
- 3)可以使用pypi
- 輸出:
- 1)xxxx,您的BMI:25.52
- 2)xxxx,您的體重過重
- 錯誤:
格式錯誤:xxxxxxxxxxxxx

In [5]:
import pyinputplus as pyip

def bmi(weight: float, height: float) -> float:
    return weight / (height / 100) ** 2
def get_status(bmi: float) -> str:
    if bmi < 18.5:
        result = '體重過輕'
    elif bmi < 24:
        result = '體重正常'
    elif bmi < 27:
        result = '體重過重'
    elif bmi < 30:
        result = '輕度肥胖'
    elif bmi < 35:
        result = '中度肥胖'
    else:
        result = '重度肥胖'
    return result

try:
    name = input('請輸入姓名:');
    height = pyip.inputFloat('請輸入身高(120~230)(cm):', min = 120, max = 230)
    weight = pyip.inputFloat('請輸入體重(40~170)(kg):', min = 40, max = 170)
    bmi_value = bmi(weight, height)
    print(f'您的身高為{height}公分')
    print(f'您的體重為{weight}公斤')
    print(f'{name}, 您的BMI為:{bmi_value:.2f}')
    print(f'{name}, 您屬於:{get_status(bmi_value)}')

except Exception as e:
    print(f'格式錯誤:{e}')

請輸入身高(120~230)(cm):請輸入體重(40~170)(kg):您的身高為180.0公分
您的體重為80.0公斤
洪偉傑, 您的BMI為:24.69
洪偉傑, 您屬於:體重過重


import pyinputplus as pyip: 導入了名為 pyinputplus 的模組，並使用 pyip 作為簡稱。

def bmi(weight: float, height: float) -> float:: 定義了一個函式 bmi，接受兩個參數 weight（體重）和 height（身高），並返回一個浮點數值。

return weight / (height / 100) ** 2: 計算並返回 BMI 值，BMI 公式是體重（公斤）除以身高（米）的平方。這裡的身高以公分為單位，因此在計算之前需要將其轉換為米。

def get_status(bmi: float) -> str:: 定義了一個函式 get_status，接受一個浮點數參數 bmi，並返回一個字串值。

if bmi < 18.5:: 判斷 BMI 是否小於 18.5。

result = '體重過輕': 如果 BMI 小於 18.5，則將 result 設為 '體重過輕'。

elif bmi < 24:: 如果 BMI 不小於 18.5，且小於 24。

result = '體重正常': 將 result 設為 '體重正常'。

重複類似的步驟，根據 BMI 值設置對應的 result。

return result: 返回計算出的健康狀態。

try:: 開始一個錯誤處理的區塊。

name = input('請輸入姓名:');: 提示用戶輸入姓名，並將其賦值給 name 變數。

height = pyip.inputFloat('請輸入身高(120~230)(cm):', min=120, max=230): 使用 pyinputplus 提供的 inputFloat 函式，提示用戶輸入身高並進行驗證，將其賦值給 height 變數。

類似地，使用 pyinputplus 提供的 inputFloat 函式提示用戶輸入體重並進行驗證，將其賦值給 weight 變數。

bmi_value = bmi(weight, height): 呼叫 bmi 函式計算 BMI 值，將結果賦值給 bmi_value 變數。

print(f'您的身高為{height}公分'): 印出使用者輸入的身高。

print(f'您的體重為{weight}公斤'): 印出使用者輸入的體重。

print(f'{name}, 您的BMI為:{bmi_value:.2f}'): 印出使用者的姓名和計算得到的 BMI 值，並保留兩位小數。

print(f'{name}, 您屬於:{get_status(bmi_value)}'): 印出使用者的姓名和根據 BMI 值得到的健康狀態。

except Exception as e:: 如果在 try 區塊中出現錯誤，執行這個區塊。

print(f'格式錯誤:{e}'): 印出錯誤訊息，顯示錯誤的詳細資訊。

In [10]:
#自己練習
import pyinputplus as py

def bmi(weight:int|float,heigh:int|float):
    return weight / (heigh / 100) **2
def get_status(bmi:int|float):
    if bmi <18.5:
        result="體重過輕"
    elif bmi < 24:
        result="體重健康"
    elif bmi < 27:
        result="體重過重"
    elif bmi < 30:
        result="輕度肥胖"
    elif bmi < 35:
        result="中度肥胖"
    else:
        result="種度肥胖"
    return result

try:
    name=input("請輸入姓名:")
    height=py.inputFloat("請輸入身高(cm):",min=1,max=200)
    weight=py.inputFloat("請輸入體重(kg):",min=1,max=200)
    bmi_show=bmi(weight,height)
    print(f"身高為{height}")
    print(f"體重為{weight}")
except Exception as e:
    print(f"發生錯誤{e}")


print(f"{name},您的bmi為{bmi_show:.2f}，您{get_status(bmi_show)}")

請輸入身高(cm):請輸入體重(kg):身高為180.0
體重為50.0
洪偉傑,您的bmi為15.43，您體重過輕
